// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.5
// source: interviewSchedule.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          // ID
	CompanyName     string `protobuf:"bytes,2,opt,name=companyName,proto3" json:"companyName,omitempty"`         // 公司名称
	ApproveTime     string `protobuf:"bytes,3,opt,name=approveTime,proto3" json:"approveTime,omitempty"`         // 投递时间
	Post            string `protobuf:"bytes,4,opt,name=post,proto3" json:"post,omitempty"`                       // 岗位
	FirstInterview  string `protobuf:"bytes,5,opt,name=firstInterview,proto3" json:"firstInterview,omitempty"`   // 一面
	SecondInterview string `protobuf:"bytes,6,opt,name=secondInterview,proto3" json:"secondInterview,omitempty"` // 二面
	ThirdInterview  string `protobuf:"bytes,7,opt,name=thirdInterview,proto3" json:"thirdInterview,omitempty"`   // 三面
	ExtraInterview  string `protobuf:"bytes,8,opt,name=extraInterview,proto3" json:"extraInterview,omitempty"`   // 更多面试
	Exam            string `protobuf:"bytes,9,opt,name=exam,proto3" json:"exam,omitempty"`                       // 笔试
	UpdateTime      string `protobuf:"bytes,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`          // 更新时间
	CreateTime      string `protobuf:"bytes,11,opt,name=createTime,proto3" json:"createTime,omitempty"`          // 创建时间
}

func (x *ScheduleRecord) Reset() {
	*x = ScheduleRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRecord) ProtoMessage() {}

func (x *ScheduleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRecord.ProtoReflect.Descriptor instead.
func (*ScheduleRecord) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScheduleRecord) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *ScheduleRecord) GetApproveTime() string {
	if x != nil {
		return x.ApproveTime
	}
	return ""
}

func (x *ScheduleRecord) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *ScheduleRecord) GetFirstInterview() string {
	if x != nil {
		return x.FirstInterview
	}
	return ""
}

func (x *ScheduleRecord) GetSecondInterview() string {
	if x != nil {
		return x.SecondInterview
	}
	return ""
}

func (x *ScheduleRecord) GetThirdInterview() string {
	if x != nil {
		return x.ThirdInterview
	}
	return ""
}

func (x *ScheduleRecord) GetExtraInterview() string {
	if x != nil {
		return x.ExtraInterview
	}
	return ""
}

func (x *ScheduleRecord) GetExam() string {
	if x != nil {
		return x.Exam
	}
	return ""
}

func (x *ScheduleRecord) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *ScheduleRecord) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{1}
}

func (x *GetScheduleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_interview_proto protoreflect.FileDescriptor

var file_interview_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x22, 0xee, 0x02, 0x0a,
	0x0e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12,
	0x28, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x68, 0x69,
	0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x74, 0x68, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65,
	0x77, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x61,
	0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x61, 0x6d, 0x12, 0x1e, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2e, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x54, 0x0a,
	0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x69, 0x65, 0x77, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_interview_proto_rawDescOnce sync.Once
	file_interview_proto_rawDescData = file_interview_proto_rawDesc
)

func file_interview_proto_rawDescGZIP() []byte {
	file_interview_proto_rawDescOnce.Do(func() {
		file_interview_proto_rawDescData = protoimpl.X.CompressGZIP(file_interview_proto_rawDescData)
	})
	return file_interview_proto_rawDescData
}

var file_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interview_proto_goTypes = []interface{}{
	(*ScheduleRecord)(nil),     // 0: interviewSchedule.ScheduleRecord
	(*GetScheduleRequest)(nil), // 1: interviewSchedule.GetScheduleRequest
}
var file_interview_proto_depIdxs = []int32{
	1, // 0: interviewSchedule.Interview.GetSchedule:input_type -> interviewSchedule.GetScheduleRequest
	0, // 1: interviewSchedule.Interview.GetSchedule:output_type -> interviewSchedule.ScheduleRecord
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interview_proto_init() }
func file_interview_proto_init() {
	if File_interview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interview_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interview_proto_goTypes,
		DependencyIndexes: file_interview_proto_depIdxs,
		MessageInfos:      file_interview_proto_msgTypes,
	}.Build()
	File_interview_proto = out.File
	file_interview_proto_rawDesc = nil
	file_interview_proto_goTypes = nil
	file_interview_proto_depIdxs = nil
}
