// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package tableobj

import (
	"time"
)

const TableNameTInterviewSchedule = "t_interview_schedule"

// TInterviewSchedule 面试时间表
type TInterviewSchedule struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyName     string     `gorm:"column:companyName;not null;comment:公司名称" json:"companyName"`                         // 公司名称
	ApproveTime     *time.Time `gorm:"column:approveTime;comment:投递时间" json:"approveTime"`                                  // 投递时间
	Post            *string    `gorm:"column:post;comment:岗位" json:"post"`                                                  // 岗位
	FirstInterview  *string    `gorm:"column:firstInterview;comment:一面" json:"firstInterview"`                              // 一面
	SecondInterview *string    `gorm:"column:secondInterview;comment:二面" json:"secondInterview"`                            // 二面
	ThirdInterview  *string    `gorm:"column:thirdInterview;comment:三面" json:"thirdInterview"`                              // 三面
	ExtraInterview  *string    `gorm:"column:extraInterview;comment:更多面试" json:"extraInterview"`                            // 更多面试
	Exam            *string    `gorm:"column:exam;comment:笔试" json:"exam"`                                                  // 笔试
	UpdateTime      time.Time  `gorm:"column:updateTime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	CreateTime      time.Time  `gorm:"column:createTime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
}

// TableName TInterviewSchedule's table name
func (*TInterviewSchedule) TableName() string {
	return TableNameTInterviewSchedule
}
